### ISSUE TITLE
Release wbids 0.1.0

### ISSUE THREAD

**Issue by christophscheuch** [Teal-Insights/r-wbids#31]
I decided to exclude both `econid` and `wbwdi` for the initial release. Both should be on CRAN if they are included in any way in the DESCRIPTION file. `econid` still needs some time to mature for a CRAN release. `wbwdi` should be released jointly with other stuff that provide more justification for a new WDI package. 

First release:

* [x] `usethis::use_news_md()`
* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#sec-code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] `usethis::use_github_links()`
* [x] `urlchecker::url_check(parallel = FALSE)`
* [x] `devtools::build_readme()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `git push`
* [ ] ~~Draft blog post~~

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [ ] ~~Finish & publish blog post~~
* [ ] ~~Add link to blog post in pkgdown news menu~~
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version(push = TRUE)`
* [x] `usethis::use_news_md()`
* [ ] Share on social media

**Comment by christophscheuch** [comment]
@t-emery I have prepared the packages for the initial CRAN submission, but you have to submit it as the maintainer. I suggest that you pull the status quo from the branch in the PR and review DESCRIPTION and README because I made a few changes: https://github.com/Teal-Insights/r-wbids/pull/38. In particular, I think it makes sense to describe the package as a stand-alone tool at the moment rather than relating it to packages that we are planing to release in the future. 

Once you are ready to submit, please call `devtools::submit_cran()` and then confirm the email that you receive. Afterwards, we keep the fingers crossed because some parts of the CRAN submission process are highly specific and can be missed even after thorough reviews and automatic checks 😄

**Comment by t-emery** [comment]
Amazing!I’ll get this started today. Thanks for all of your awesome work on this!Sent from my iPhoneOn Nov 14, 2024, at 6:00 AM, Christoph Scheuch ***@***.***> wrote:﻿
@t-emery I have prepared the packages for the initial CRAN submission, but you have to submit it as the maintainer. I suggest that you pull the status quo from the branch in the PR and review DESCRIPTION and README because I made a few changes: #38. In particular, I think it makes sense to describe the package as a stand-alone tool at the moment rather than relating it to packages that we are planing to release in the future.
Once you are ready to submit, please call devtools::submit_cran() and then confirm the email that you receive. Afterwards, we keep the fingers crossed because some parts of the CRAN submission process are highly specific and can be missed even after thorough reviews and automatic checks 😄

**Comment by christophscheuch** [comment]
I'll close the issue once the package is available on CRAN and the other to-do's in the first comment can be done :)

**Comment by chriscarrollsmith** [comment]
> I'll close the issue once the package is available on CRAN and the other to-do's in the first comment can be done :)
> 
> EDIT: ah I just saw that you merged the PR. In the future, we should submit from the release branch and merge the PR once CRAN has accepted the submission.

Sorry about that; my fault. I will document the release workflow so we know how to do it in the future. I appreciate your detailed checklist above.

**Comment by christophscheuch** [comment]
> Sorry about that; my fault. I will document the release workflow so we know how to do it in the future. I appreciate your detailed checklist above.

The checklist is the outcome of the single line that I already added to the release workflow here 😁 https://github.com/Teal-Insights/r-wbids/wiki/Development-Workflow#cran-releases

**Comment by christophscheuch** [comment]
Party 🥳 
- CRAN release: https://cran.r-project.org/web/packages/wbids/index.html
- GitHub release: https://github.com/Teal-Insights/r-wbids/releases/tag/v0.1.0
- main branch now runs on dev version 0.1.0.9000. Ideally, with each PR, we increment the version number.
