### ISSUE TITLE
Enhancement: Change `ids_get()` Default Parameters for `counterparts` and `start_date` to Reduce Data Volume and Align with User Needs

### ISSUE THREAD

**Issue by t-emery** [Teal-Insights/r-wbids#50]
#### **Proposed Changes**
We propose the following updates to the default parameters in the `ids_get` function:
1. **Change default for `counterparts`**:  
   - Current default: `"all"`  
   - Proposed default: `"World"`  
   - Rationale: Most users are likely interested in the overall aggregated debt statistics for the world (`"World"`). Switching the default to `"World"` reduces the data volume significantly while aligning the output with the typical use case. Documentation and examples will clearly explain how users can still retrieve data for all counterparts by explicitly setting `counterparts = "all"`.

2. **Change default for `start_date`**:  
   - Current default: `NULL` (fetches data from the entire range, starting in 1970).  
   - Proposed default: `2000`  
   - Rationale: The majority of users are focused on modern data, starting from the 21st century. Fetching data from 1970 onward unnecessarily increases the data volume for most use cases. Setting a default of `2000` aligns with user needs while still allowing advanced users to explicitly request earlier data by setting `start_date = 1970`.

---

#### **Justification for Changes**
1. **Impact on Data Volume**:  
   With the current defaults, a single data series for all geographies generates a massive dataset:
   - **Years**: 52 (1970–2022)  
   - **Geographies**: 136  
   - **Counterpart Areas**: 303  
   - **Total Observations**:  
     \[
     52 \times 136 \times 303 = 2,142,816 \text{ observations}
     \]

   After the proposed changes, the dataset would be significantly smaller:
   - **Years**: 22 (2000–2022)  
   - **Geographies**: 136  
   - **Counterpart Areas**: 1 (World)  
   - **Total Observations**:  
     \[
     22 \times 136 \times 1 = 2,992 \text{ observations}
     \]

   This is a **reduction of over 99%** in the number of observations for the default scenario, making the API calls more manageable for users and reducing the load on the server.

2. **Alignment with Typical Use Case**:  
   - Most users are not analyzing individual counterpart areas for historical data stretching back to 1970. Instead, they are likely interested in aggregated statistics for the world in recent years.
   - The proposed defaults provide data more aligned with user expectations, reducing unnecessary complexity and making the function easier to use out of the box.

3. **Flexibility for Advanced Users**:  
   - By explicitly setting `counterparts = "all"` and `start_date = 1970`, advanced users can still retrieve the full dataset when needed.
   - Documentation and examples will illustrate how to configure these parameters to access the full range of data.

---

#### **Action Items**
1. Update the default values for `counterparts` and `start_date` in the `ids_get` function.
2. Revise the documentation to:
   - Clearly state the new defaults.
   - Provide examples demonstrating how to retrieve data for all counterpart areas and the full time range (starting from 1970).
3. Update test cases to reflect the new defaults and ensure backward compatibility.

---

#### **Expected Benefits**
- Improved alignment with user needs by providing modern, aggregated data as the default output.
- Significant reduction in data volume for default scenarios, making API calls faster and more manageable.
- Maintained flexibility for advanced users to access the full dataset when necessary.  

---

#### **Feedback Requested**
We welcome any feedback on this proposal, particularly around the new defaults and any edge cases we may not have considered.

**Comment by christophscheuch** [comment]
Sounds great, I approve :)

**Comment by t-emery** [comment]
I wanted to finish this up myself, but alas, I've got too much on my plate in the next 48 hrs.   @chriscarrollsmith can you address any of the outstanding comments and do whatever you think needs to get done to get this over the line and merged into main?   Let me know if there is any info you need from me.  Thanks!

**Comment by chriscarrollsmith** [comment]
Sure, will do. Probably tomorrow before I get to it, though!
