### ISSUE TITLE
Bug:  ids_get() fails due to potential rate-limiting or timeout

### ISSUE THREAD

**Issue by t-emery** [Teal-Insights/r-wbids#51]
The function ids_get() fails when querying large combinations of geographies and series, likely due to rate-limiting or excessive requests. I suspect the issue stems from the large number of API calls being made in parallel without accounting for server limits.

Steps to Reproduce:

geography_vec <- c("AFG", "AGO", "BDI", "BEN", "BFA", "BGD", "BOL", "BTN", "CAF", "CIV", "CMR", "COD", "COG", "COM", "CPV", "DJI", "EGY", "ERI", "ETH", "GHA", "GIN", "GMB", "GNB", "HND", "HTI", "IND", "JOR", "KEN", "KGZ", "KHM", "LAO", "LBN", "LBR", "LKA", "LSO", "MAR", "MDG", "MLI", "MMR", "MOZ", "MRT", "MWI", "NER", "NGA", "NIC", "NPL", "PAK", "PHL", "PNG", "RWA", "SDN", "SEN", "SLB", "SLE", "SOM", "STP", "SWZ", "SYR", "TCD", "TGO", "TJK", "TLS", "TUN", "TZA", "UGA", "UZB", "VNM", "VUT", "WSM", "YEM", "ZMB", "ZWE")

series_vec <- c("DT.AMT.OFFT.CD", "DT.AMT.PRVT.CD", "DT.AMT.DPPG.CD", "DT.AMT.BLAT.CD", "DT.AMT.BLTC.CD", "DT.AMT.PBND.CD", "DT.AMT.PCBK.CD", "DT.AMT.MLAT.CD", "DT.AMT.MLTC.CD", "DT.AMT.PROP.CD", "DT.DIS.OFFT.CD", "DT.DIS.PRVT.CD", "DT.DIS.DPPG.CD", "DT.DIS.BLAT.CD", "DT.DIS.BLTC.CD", "DT.DIS.PBND.CD", "DT.DIS.PCBK.CD", "DT.DIS.MLAT.CD", "DT.DIS.MLTC.CD", "DT.DIS.PROP.CD", "DT.INT.OFFT.CD", "DT.INT.PRVT.CD", "DT.INT.DPPG.CD", "DT.INT.BLAT.CD", "DT.INT.BLTC.CD", "DT.INT.PBND.CD", "DT.INT.PCBK.CD", "DT.INT.MLAT.CD", "DT.INT.MLTC.CD", "DT.INT.PROP.CD", "DT.NFL.DPPG.CD", "DT.NFL.OFFT.CD", "DT.NFL.PRVT.CD", "DT.NFL.BLAT.CD", "DT.NFL.BLTC.CD", "DT.NFL.PBND.CD", "DT.NFL.PCBK.CD", "DT.NFL.MLAT.CD", "DT.NFL.MLTC.CD", "DT.NFL.PROP.CD")

debt_service <- ids_get(
  geographies = geography_vec,
  series = series_vec,
  counterparts = c("WLD", "730"),
  start_date = 2010,
  end_date = 2023
)
Observed Behavior: The request fails with the following error:

Error in `pmap()`:
ℹ In index: 50989.
Caused by error in `httr2::req_perform()`:
! Failed to perform HTTP request.
Caused by error in `curl::curl_fetch_memory()`:
! Timeout was reached [api.worldbank.org]: Operation too slow. Less than 1 bytes/sec transferred the last 600 seconds
Backtrace:
  1. wbids::ids_get(...)
  2. purrr::pmap_df(...)
  3. purrr::pmap(.l, .f, ...)
  4. purrr:::pmap_("list", .l, .f, ..., .progress = .progress)
  8. wbids (local) .f(...)
     ...
 11. httr2::req_perform(req)
 12. base::tryCatch(...)
 13. base (local) tryCatchList(expr, classes, parentenv, handlers)
 14. base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 15. value[[3L]](cond)

Expected Behavior: The function should either:

- Gracefully handle rate-limiting by implementing a retry mechanism or delays between requests.
- Provide a clear error message indicating the API has rejected the request due to rate limits.

Potential Solutions:

- Add rate-limiting awareness:
- Implement request pacing to avoid overwhelming the API.
- Use headers (e.g., X-Rate-Limit-Remaining, if available) to detect limits.
- Introduce batch querying:
- Divide large queries into smaller batches and allow users to specify batch size.
- Retry Logic:
- Retry failed requests using exponential backoff.
- Environment:

> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: aarch64-apple-darwin20
Running under: macOS 15.1.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1] wbwdi_0.1.0        tealviz_0.0.0.9001 lubridate_1.9.3    forcats_1.0.0      stringr_1.5.1      dplyr_1.1.4        purrr_1.0.2       
 [8] readr_2.1.5        tidyr_1.3.1        tibble_3.2.1       ggplot2_3.5.1      tidyverse_2.0.0    wbids_0.1.0       

loaded via a namespace (and not attached):
 [1] jsonlite_1.8.9    gtable_0.3.6      compiler_4.4.1    renv_1.0.7        tidyselect_1.2.1  systemfonts_1.1.0 scales_1.3.0     
 [8] R6_2.5.1          generics_0.1.3    curl_6.0.1        datapasta_3.1.1   httr2_1.0.7       knitr_1.49        munsell_0.5.1    
[15] pillar_1.9.0      tzdb_0.4.0        rlang_1.1.4       utf8_1.2.4        stringi_1.8.4     xfun_0.49         timechange_0.3.0 
[22] cli_3.6.3         withr_3.0.2       magrittr_2.0.3    grid_4.4.1        rstudioapi_0.17.1 rappdirs_0.3.3    hms_1.1.3        
[29] lifecycle_1.0.4   vctrs_0.6.5       evaluate_1.0.1    glue_1.8.0        fansi_1.0.6       colorspace_2.1-1  tools_4.4.1      
[36] pkgconfig_2.0.3

**Comment by christophscheuch** [comment]
Since the World Bank API is opaque about limits, I'd just go with the retry using exponential backoff. If that fails after 10 tries, then return an informative error message (e.g. "API request for geography XY and series YZ failed after 10 retries. Please try again later.")

**Comment by chriscarrollsmith** [comment]
I'll start with exponential backoff. I think there are some other things to be done here that I learned from working on imfr, but let's get the easy fix out first.

**Comment by chriscarrollsmith** [comment]
I implemented exponential backoff the same way as in your r-wbwdi package, @christophscheuch, but it doesn't seem to be working. At least, I couldn't get it to actually exhibit this retry behavior in the (failing) test titled "perform_request retries on server errors", where I mocked a 503 response. Have you verified that r-wbwdi is actually doing retries? 

(It's late, so maybe I just screwed up somewhere and the answer will be obvious in the morning, lol.)

**Comment by christophscheuch** [comment]
Phew, this is a tough one to mock, I didn't do it.. A played around with it a bit, but I don't have a solution. Does it work if you brute-force it, i.e. send requests to the API like crazy?

**Comment by chriscarrollsmith** [comment]
I think it's the function behavior that's the problem, not the mock setup, but I will do some testing with print statements to verify. I had Claude spin up a local API that always returns a 503. Took me all of 1 minute. :)

**Comment by chriscarrollsmith** [comment]
Okay, I was able to confirm that the function does do exponential backoff in a live API request, so the mock is evidently just not getting the job done.

**Comment by chriscarrollsmith** [comment]
I tried a few different approaches to creating unit tests for the retry behavior, and ultimately I gave up. In any case, I suppose it's something that's more proper to test in the httr2 library itself. I did, at least, confirm that the retry behavior does work on an actual API.

Teal's example is still taking forever, though, so I am keep working this problem from some different angles.

**Comment by chriscarrollsmith** [comment]
It took some searching in their documentation, but I finally found [this](https://datahelpdesk.worldbank.org/knowledgebase/articles/1886674-new-features-and-enhancements-in-the-v2-api), about requesting multiple resources with a single API call:

> Enhancements in JSON responses for indicator data queries
> 
> Responses in JSON format are available by using format=json in the API call.
> 
> Example: https://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?format=json
> 
> The following improvements have been made to JSON responses:
> 
>     Supports native JSON parser.
>     The “fact” data type is now a number.
>     Multiple indicators data: Data can be queried for multiple indicators from a particular data source by providing source ID and indicator codes separated by ; (semicolon).
>         Example: https://api.worldbank.org/v2/country/chn;ago/indicator/SI.POV.DDAY;SP.POP.TOTL?source=2
>         Note: A maximum of 60 indicators can be included with a maximum of 1,500 characters allowed between two /’s (back-slashes). A maximum of 4,000 characters are allowed in the entire URL.

So it looks like we can request multiple resources by separating them with semicolons rather than doing separate API calls for each one. I did the following quick test to request two separate years, and it looks like it works:

``` R
ourceRequest <- request("http://api.worldbank.org/v2/sources/6/country/ZMB/series/DT.DOD.DPPG.CD/time/YR2019;YR2020") %>%
  req_url_query(per_page = 15000, format = "json")

sourceResponse <- sourceRequest %>%
  req_perform() %>%
  resp_body_string()

sourceJSON <- fromJSON(sourceResponse, flatten = TRUE)

sourceJSON$source
```

**Comment by christophscheuch** [comment]
I was too afraid to implement this because of the following limit and all the overhead in checks and splitting queries it creates: 
_Note: A maximum of 60 indicators can be included with a maximum of 1,500 characters allowed between two /’s (back-slashes). A maximum of 4,000 characters are allowed in the entire URL._

Maybe a quick improvement is to increase the per_page parameter to 32500 (the maximum). 

I also don't believe that downloading large amounts of data need to be particularly fast, people typically do it once (I hope). Eventually, it'd be better to just host the data at a new data source that is faster than the World Bank API (e.g. MotherDuck).

**Comment by t-emery** [comment]
Fwiw, requests of the size I was making may still be one where it makes sense to use ids_bulk() even after we’ve solved the rate limiting issues. If that is the case, users will probably using ids_bulk() a lot. I have some good preliminary ideas about how to improve the user experience for that function that I will share as an issue as time allows.Sent from my iPhoneOn Dec 9, 2024, at 1:49 AM, Christoph Scheuch ***@***.***> wrote:﻿
I was too afraid to implement this because of the following limit and all the overhead in checks and splitting queries it creates:
Note: A maximum of 60 indicators can be included with a maximum of 1,500 characters allowed between two /’s (back-slashes). A maximum of 4,000 characters are allowed in the entire URL.
Maybe a quick improvement is to increase the per_page parameter to 32500 (the maximum).
I also don't believe that downloading large amounts of data need to be particularly fast, people typically do it once (I hope). Eventually, it'd be better to just host the data at a new data source that is faster than the World Bank API (e.g. MotherDuck).

**Comment by chriscarrollsmith** [comment]
> I was too afraid to implement this because of the following limit and all the overhead in checks and splitting queries it creates: 
> _Note: A maximum of 60 indicators can be included with a maximum of 1,500 characters allowed between two /’s (back-slashes). A maximum of 4,000 characters are allowed in the entire URL._
> 
> Maybe a quick improvement is to increase the per_page parameter to 32500 (the maximum). 
> 
> I also don't believe that downloading large amounts of data need to be particularly fast, people typically do it once (I hope). Eventually, it'd be better to just host the data at a new data source that is faster than the World Bank API (e.g. MotherDuck). 

The one-at-a-time download approach is unfortunately just way too slow and way too likely to get rate-limited (as Teal's example shows and my efforts to replicate his experience confirm). If someone requests more than 60, we can just raise an error that says 60 is the max and advises them to use the bulk download function instead.

**Comment by christophscheuch** [comment]
Allowing up to 60 / max 1500 characters between slashes / max 4000 in URL and throwing an informative error otherwise sounds fine for me.

**Comment by chriscarrollsmith** [comment]
I will tackle that this morning.

**Comment by chriscarrollsmith** [comment]
I just ran Teal's query with the updated function, and I can confirm that it runs in about 15 seconds and returns about 81,000 rows.

**Comment by t-emery** [comment]
Amazing!Sent from my iPhoneOn Dec 9, 2024, at 1:14 PM, Christopher Carroll Smith ***@***.***> wrote:﻿
I just ran Teal's query with the updated function, and I can confirm that it runs successfully in about 15 seconds and returns about 81,000 rows.
